### ISSUE TITLE
Bad variable name when providing .regrid with weight_file argument

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/x4c#1]
```diff
$ git diff
diff --git a/x4c/core.py b/x4c/core.py
index d3b6337..9bcb294 100644
--- a/x4c/core.py
+++ b/x4c/core.py
@@ -98,7 +98,7 @@ def regrid(self, dlon=1, dlat=1, weight_file=None, gs='T', method='bilinear', pe

         if weight_file is not None:
             # using a user-provided weight file for any unsupported regridding
-            ds_rgd = utils.regrid_cam_se(ds, weight_file=weight_file)
+            ds_rgd = utils.regrid_cam_se(self.ds, weight_file=weight_file)
         else:
             if grid[:2] == 'ne':
                 # SE grid
```

If `weight_file` is not `None`, the first argument in the call to `utils.regrid_cam_se()` should be `self.ds`, not `ds`. I can open a PR tomorrow, just want to record this issue while I'm thinking about it.

**Comment by fzhu2e** [comment]
Hi Mike, thanks for catching this! I've added you as a collaborator of this repo and you can now directly push your updates if it feels cumbersome to submit a PR given that the fix is straightforward.

I'll fix this one to save some trouble.
